# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: ensor

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ensor
    main: .
    binary: ensor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/Pratyay360/ensor/cmd.version={{.Version}}

archives:
  - id: default
    ids:
      - ensor
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: "Bug fixes"
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

nfpms:
  - id: deb-rpm-apk
    package_name: ensor
    description: "Censor secrets in your code"
    homepage: "https://github.com/Pratyay360/ensor"
    maintainer: "Pratyay360 <pratyaymustafi@outlook.com>"
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk

release:
  github:
    owner: Pratyay360
    name: ensor
  footer: |-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

snapshot:
  version_template: "{{ incpatch .Version }}-next"
