name: ci

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/jdx/mise:latest
    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: Install dependencies & building
        run: |
            mise deps
            mise run fetch
            mise run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
